"""empty message

Revision ID: 34cbd59afe06
Revises: bc10f06650ee
Create Date: 2020-06-19 12:51:41.574118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34cbd59afe06'
down_revision = 'bc10f06650ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'charity',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'charity',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
