"""empty message

Revision ID: 981ca5ab3deb
Revises: 32e51d41c301
Create Date: 2020-07-30 13:39:41.450368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981ca5ab3deb'
down_revision = '32e51d41c301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_charity_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_charity_key', 'users', ['charity'])
    # ### end Alembic commands ###
